apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produto
spec:
  selector:
    matchLabels:
      name: lbl-api-produto
  replicas: 2
  template:
    metadata:
      labels:
        name: lbl-api-produto
    spec:
      containers:
        - name: api-produto
          resources:
            requests:
              memory: 256Mi
              cpu: 400m
            limits:
              memory: 512Mi
              cpu: 800m
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8091
            initialDelaySeconds: 25
            periodSeconds: 2
            timeoutSeconds: 2
            #Informa quantas vezes uma falha deve ocorrer para a verificação ser considerada com falha e o pod da aplicação sofrer um restart ou não receber tráfego.
            failureThreshold: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8091
            initialDelaySeconds: 25
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          image: wesleyhinsch/api-produto:v1.0.0
          env:
            - name: MYSQL_SERVICE
              value: service-k8s-mysql
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-db-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-password
          imagePullPolicy: Always
          ports:
            - name: api-produto
              containerPort: 8091
              protocol: TCP
      imagePullSecrets:
        - name: api-produto
---
apiVersion: v1
kind: Service
metadata:
  name: service-api-produto
  labels:
    name: lbl-api-produto
spec:
  selector:
    name: lbl-api-produto
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30091
  type: NodePort
  #type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: lbl-k8s-mysql
spec:
  selector:
    matchLabels:
      name: lbl-k8s-mysql
  template:
    metadata:
      labels:
        name: lbl-k8s-mysql
    spec:
      containers:
        - name: mysql
          resources:
            requests:
              memory: 256Mi
              cpu: 1000m
            limits:
              memory: 256Mi
              cpu: 1000m
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password_root
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-db-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-password
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: k8s-mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: k8s-mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password_root: YWRtaW4=
  mysql-username: bnNzZnVzcg==
  mysql-password: bnNzZnBhc3N3ZA==
  mysql-db-name: bnNzZmRi
---
apiVersion: v1
kind: Service
metadata:
  name: service-k8s-mysql
  labels:
    name: lbl-k8s-mysql
spec:
  selector:
    name: lbl-k8s-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30006
  type: NodePort
